"use client";

import {
  ChevronDown,
  Copy,
  Download,
  ExternalLink,
  FileCheck,
  Link2,
} from "lucide-react";
import { useEffect, useState } from "react";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type {
  AgentProfile,
  BehaviorEvent,
  BehaviorEventType,
} from "@/lib/mock/types";
import {
  agentMoniker,
  digestActionLabel,
  digestRowDotClass,
  digestStatusPhrase,
  humanEventKind,
  relativeTime,
  verificationHuman,
} from "@/lib/mock/narrative";
import { baseTxUrl } from "@/lib/basescan";

function RelativeTime({ ts, paused }: { ts: number; paused?: boolean }) {
  /** Empty until client mount — avoids SSR vs browser clock mismatch in relativeTime(). */
  const [label, setLabel] = useState("");

  useEffect(() => {
    const tick = () => setLabel(relativeTime(ts));
    tick();
    if (paused) return;
    const id = window.setInterval(tick, 60_000);
    return () => window.clearInterval(id);
  }, [ts, paused]);

  return (
    <span className="text-xs text-white/45" suppressHydrationWarning>
      {label || "—"}
    </span>
  );
}

function formatUtcHms(ts: number): string {
  return (
    new Intl.DateTimeFormat("en-GB", {
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
      timeZone: "UTC",
      hour12: false,
    }).format(new Date(ts * 1000)) + " UTC"
  );
}

function eventTypeMono(type: BehaviorEventType, summary: string): string {
  const a = digestActionLabel(type, summary);
  return a.replace(/\s+/g, "_").toUpperCase();
}

function buildTrustReceiptText(event: BehaviorEvent, agentName: string) {
  const v = verificationHuman(event.verificationStatus);
  return [
    "AgentLedger — Trust receipt",
    "",
    `Agent: ${agentName}`,
    `Event: ${humanEventKind(event.type)}`,
    `Summary: ${event.summary}`,
    `Verification: ${v.label}`,
    `Risk score: ${event.riskScore}/100`,
    `Record ID: ${event.anchored.txHash}`,
    `Payload CID: ${event.payloadCid}`,
    `IPFS: ${event.anchored.ipfsCid}`,
    event.anchored.merkleRoot
      ? `Merkle: ${event.anchored.merkleRoot}`
      : "",
    "",
    "Generated by AgentLedger — not legal advice.",
  ]
    .filter(Boolean)
    .join("\n");
}

function ProofPanel({
  event,
  agentName,
}: {
  event: BehaviorEvent;
  agentName: string;
}) {
  const v = verificationHuman(event.verificationStatus);
  const whenUtc = new Intl.DateTimeFormat("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: "UTC",
    timeZoneName: "short",
  }).format(new Date(event.timestampUnix * 1000));

  return (
    <div className="overflow-hidden border-t border-white/10 bg-black/20">
      <div className="space-y-4 p-5">
        <div className="flex items-start gap-2 text-sm text-white/75">
          <FileCheck className="mt-0.5 h-4 w-4 shrink-0 text-[#06B6D4]" />
          <p>
            This entry is backed by a{" "}
            <span className="text-white">Verified Record</span> you can share
            with legal, finance, or a partner — like a receipt, not a cryptography
            tutorial.
          </p>
        </div>
        <div className="rounded-lg border border-white/10 bg-[var(--bg-base)]/80 p-4">
          <p className="text-xs font-medium uppercase tracking-wider text-white/45">
            Receipt summary
          </p>
          <ul className="mt-3 space-y-2 text-sm text-white/80">
            <li className="flex justify-between gap-4">
              <span className="text-white/50">Status</span>
              <span>{v.label}</span>
            </li>
            <li className="flex flex-col gap-1 sm:flex-row sm:justify-between sm:gap-4">
              <span className="shrink-0 text-white/50">When (UTC)</span>
              <span className="min-w-0 break-words text-right">{whenUtc}</span>
            </li>
          </ul>
        </div>
        <div>
          <p className="text-xs font-medium uppercase tracking-wider text-white/45">
            Technical proof (optional)
          </p>
          <p className="mt-2 text-xs text-white/45">
            For auditors or engineers. Not required to understand what happened.
          </p>
          <dl className="mt-3 space-y-3 font-mono text-[11px] text-white/70">
            <div>
              <dt className="text-white/40">Record ID</dt>
              <dd className="mt-1 break-all text-[#06B6D4]">
                {event.anchored.txHash}
              </dd>
            </div>
            <div>
              <dt className="text-white/40">Record fingerprint</dt>
              <dd className="mt-1 break-all text-[#c4b5fd]">
                {event.payloadCid}
              </dd>
            </div>
            <div>
              <dt className="text-white/40">Archive copy</dt>
              <dd className="mt-1 break-all text-[#c4b5fd]">
                {event.anchored.ipfsCid}
              </dd>
            </div>
            {event.anchored.merkleRoot ? (
              <div>
                <dt className="text-white/40">Integrity check</dt>
                <dd className="mt-1 break-all">{event.anchored.merkleRoot}</dd>
              </div>
            ) : null}
          </dl>
        </div>
        <div className="flex flex-wrap gap-2">
          <Button
            type="button"
            variant="default"
            size="sm"
            className="gap-1.5 text-xs"
            onClick={() => {
              const body = buildTrustReceiptText(event, agentName);
              const blob = new Blob([body], { type: "text/plain;charset=utf-8" });
              const url = URL.createObjectURL(blob);
              const a = document.createElement("a");
              a.href = url;
              a.download = `agentledger-trust-receipt-${event.id}.txt`;
              a.click();
              URL.revokeObjectURL(url);
            }}
          >
            <Download className="h-3.5 w-3.5" />
            Download trust receipt
          </Button>
          <Button
            type="button"
            variant="outline"
            size="sm"
            className="gap-1.5 font-mono text-xs"
            onClick={() =>
              void navigator.clipboard.writeText(event.anchored.txHash)
            }
          >
            <Copy className="h-3.5 w-3.5" />
            Copy verification link
          </Button>
          <Button
            type="button"
            variant="secondary"
            size="sm"
            className="gap-1.5 text-xs"
            onClick={() =>
              window.open(baseTxUrl(event.anchored.txHash), "_blank")
            }
          >
            <ExternalLink className="h-3.5 w-3.5" />
            Verify record externally →
          </Button>
        </div>
      </div>
    </div>
  );
}

function DigestRow({
  event,
  displayName,
  paused,
}: {
  event: BehaviorEvent;
  displayName: string;
  paused: boolean;
}) {
  const [open, setOpen] = useState(false);
  const moniker = agentMoniker(displayName);
  const typeUpper = eventTypeMono(event.type, event.summary);
  const v = verificationHuman(event.verificationStatus);
  const statusPhrase = digestStatusPhrase(event.verificationStatus);
  const dotClass = digestRowDotClass(event);

  return (
    <div className="border-b border-white/[0.08] last:border-0">
      <div className="flex flex-col gap-3 p-3 sm:flex-row sm:items-start sm:justify-between sm:gap-4">
        <div className="min-w-0 flex-1 space-y-2">
          <div className="flex flex-wrap items-start gap-x-2 gap-y-1 font-mono text-[11px] leading-relaxed sm:text-xs">
            <span
              className={`mt-1 inline-block h-2 w-2 shrink-0 rounded-full ${dotClass}`}
              aria-hidden
            />
            <span className="text-white/30">{formatUtcHms(event.timestampUnix)}</span>
            <span className="hidden text-white/25 sm:inline">│</span>
            <span className="text-white/60">{moniker}</span>
            <span className="text-[#06B6D4]">{typeUpper}</span>
          </div>
          <p className="pl-0 text-[13px] leading-relaxed text-white/85 sm:pl-4">
            &quot;{event.summary}&quot;
          </p>
          <p className="pl-0 font-mono text-[10px] text-white/40 sm:pl-4">
            <RelativeTime ts={event.timestampUnix} paused={paused} />
            <span className="text-white/25"> · </span>
            <span
              className={
                v.variant === "success"
                  ? "text-[#6ee7b7]"
                  : v.variant === "destructive"
                    ? "text-[#fca5a5]"
                    : "text-white/55"
              }
            >
              {statusPhrase}
            </span>
            <button
              type="button"
              className="ml-3 inline text-[#c4b5fd] underline decoration-white/20 underline-offset-2 transition-colors hover:text-white"
              onClick={() => setOpen((o) => !o)}
            >
              <Link2 className="mb-0.5 mr-1 inline h-3 w-3" />
              Verified record
            </button>
          </p>
        </div>
        <div className="flex shrink-0 flex-col gap-2 sm:items-end">
          <Button
            type="button"
            variant="outline"
            size="sm"
            className="min-h-[48px] shrink-0 gap-1 self-start border-white/[0.15] bg-transparent font-mono text-xs sm:min-h-9 sm:self-end"
            onClick={() => setOpen((o) => !o)}
            aria-expanded={open}
          >
            {"// proof"}
            <span
              className={`inline-block transition-transform duration-200 ${open ? "rotate-180" : ""}`}
            >
              <ChevronDown className="h-4 w-4" />
            </span>
          </Button>
        </div>
      </div>
      {open ? (
        <ProofPanel event={event} agentName={displayName} />
      ) : null}
    </div>
  );
}

export function DailyDigest({
  events,
  agents,
}: {
  events: BehaviorEvent[];
  agents: AgentProfile[];
}) {
  const [paused, setPaused] = useState(false);
  const sorted = [...events].sort((a, b) => b.timestampUnix - a.timestampUnix);
  const agentDisplayName = (id: string) =>
    agents.find((a) => a.id === id)?.displayName ?? "Agent";

  if (agents.length === 0) {
    return (
      <section id="todays-summary" className="scroll-mt-24 space-y-2">
        <Card className="border-white/10 bg-gradient-to-br from-[#1A1A2E]/95 to-transparent">
          <CardHeader className="pb-2">
            <CardTitle className="text-lg font-semibold">
              Today&apos;s activity summary
            </CardTitle>
            <p className="text-sm leading-relaxed text-white/55">
              Your behavioral record will appear here as soon as an agent is
              connected. Every line gets a permanent proof you can export.
            </p>
          </CardHeader>
          <CardContent className="pt-2">
            <p className="rounded-lg border border-dashed border-white/10 bg-white/[0.02] py-10 text-center text-sm text-white/50">
              No agents connected — connect above to start recording events.
            </p>
          </CardContent>
        </Card>
      </section>
    );
  }

  return (
    <section id="todays-summary" className="scroll-mt-24 space-y-2">
      <Card className="border-white/[0.08] bg-transparent shadow-none">
        <CardHeader className="pb-3">
          <CardTitle className="font-display text-lg font-semibold tracking-tight">
            Today&apos;s activity summary
          </CardTitle>
          <p className="font-mono text-[11px] text-cyan-400/70">
            {"// today_at_a_glance"}
          </p>
          <p className="mt-3 text-sm leading-relaxed text-white/70">
            Your agents were economic actors today: treasury-agent swept $12,400
            USDC, settled 3 invoices, declined 1 unauthorized payment. All within
            mandate. ✓ deal-scout evaluated 847 targets, submitted 1 LOI ($4.2M),
            was blocked from signing 1 NDA. Review needed. compliance-agent filed
            Q2 EU AI Act disclosure, flagged deal-scout for policy drift. 88
            events. ✓ rogue-scraper suspended 2h ago after credential
            exfiltration attempt. 14 violations on record.{" "}
            <span className="text-amber-200/90">2 items need your attention</span>{" "}
            →{" "}
            <button
              type="button"
              className="text-[#c4b5fd] underline decoration-white/20 underline-offset-2"
              onClick={() => {
                const el = document.getElementById("todays-summary");
                el?.scrollIntoView({ behavior: "smooth" });
              }}
            >
              Review now
            </button>
          </p>
          <p className="mt-4 text-sm leading-relaxed text-white/55">
            Terminal stream of what your agents did. Open{" "}
            <span className="text-white/75">{"// proof"}</span> for receipts and
            verified records.
          </p>
        </CardHeader>
        <CardContent className="p-0">
          <div className="overflow-hidden rounded-xl border border-white/[0.08] bg-[#0A0A0F] p-4 font-mono text-xs">
            <div className="flex flex-col gap-3 border-b border-white/[0.08] pb-3 sm:flex-row sm:items-center sm:justify-between">
              <span className="text-[11px] text-cyan-400/80">
                {"// live_event_stream.log"}
              </span>
              <div className="flex flex-wrap items-center gap-3">
                <span className="text-[11px] text-white/30">
                  {sorted.length.toLocaleString("en-US")} events in feed
                </span>
                <button
                  type="button"
                  onClick={() => setPaused((p) => !p)}
                  className="text-[11px] text-white/45 transition-colors hover:text-white"
                >
                  {paused ? "// resume" : "// pause"}
                </button>
              </div>
            </div>
            <div className="max-h-[min(70vh,720px)] overflow-y-auto pt-1 [-ms-overflow-style:none] [scrollbar-width:thin]">
              {sorted.length === 0 ? (
                <p className="py-10 text-center text-sm text-white/50">
                  No events in this window yet. Activity streams here as your
                  agents log to AgentLedger.
                </p>
              ) : (
                sorted.map((event) => (
                  <DigestRow
                    key={event.id}
                    event={event}
                    displayName={agentDisplayName(event.agentId)}
                    paused={paused}
                  />
                ))
              )}
            </div>
          </div>
        </CardContent>
      </Card>
    </section>
  );
}
