"use client";

import {
  ArrowLeft,
  Copy,
  ExternalLink,
  FileCheck,
  Share2,
} from "lucide-react";
import Link from "next/link";
import { useState } from "react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  humanEventKind,
  verificationHuman,
} from "@/lib/mock/narrative";
import type { AgentProfile, BehaviorEvent } from "@/lib/mock/types";
import { baseTxUrl } from "@/lib/basescan";

function buildTrustReceipt(agent: AgentProfile, ev: BehaviorEvent) {
  const v = verificationHuman(ev.verificationStatus);
  return [
    `AgentLedger — Trust receipt`,
    ``,
    `Agent: ${agent.displayName}`,
    `Event: ${humanEventKind(ev.type)}`,
    `Summary: ${ev.summary}`,
    `Verification: ${v.label}`,
    `Risk score: ${ev.riskScore}/100`,
    `Record ID: ${ev.anchored.txHash}`,
    `Payload CID: ${ev.payloadCid}`,
    `IPFS: ${ev.anchored.ipfsCid}`,
    ev.anchored.merkleRoot ? `Merkle: ${ev.anchored.merkleRoot}` : "",
    ``,
    `Generated by AgentLedger — not legal advice.`,
  ]
    .filter(Boolean)
    .join("\n");
}

export function AgentProfileView({
  agent,
  events,
}: {
  agent: AgentProfile;
  events: BehaviorEvent[];
}) {
  const [shareMsg, setShareMsg] = useState<string | null>(null);
  const sorted = [...events].sort((a, b) => b.timestampUnix - a.timestampUnix);

  const shareProfile = async () => {
    const text = `AgentLedger profile: ${agent.displayName} — ${agent.trustScore}% Trust Score, ${agent.totalEvents.toLocaleString()} actions on record.`;
    if (typeof navigator !== "undefined" && navigator.share) {
      try {
        await navigator.share({ title: agent.displayName, text });
        return;
      } catch {
        /* user cancelled or share failed — fall back */
      }
    }
    await navigator.clipboard.writeText(text);
    setShareMsg("Summary copied to clipboard");
    window.setTimeout(() => setShareMsg(null), 2500);
  };

  return (
    <div className="space-y-8">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <Button
            variant="ghost"
            size="sm"
            className="mb-3 -ml-2 h-8 gap-1.5 px-2 text-white/55 hover:text-white"
            asChild
          >
            <Link href="/agents">
              <ArrowLeft className="h-4 w-4" />
              All integrations
            </Link>
          </Button>
          <h1 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">
            {agent.displayName}
          </h1>
          <p className="mt-2 max-w-2xl text-base text-white/55">
            Production agent profile — policy pack, ledger trail, and verified
            records for this workspace.
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <Button
            type="button"
            variant="outline"
            size="sm"
            className="border-white/15 bg-white/5"
            onClick={() => void shareProfile()}
          >
            <Share2 className="mr-1.5 h-3.5 w-3.5" />
            Share summary
          </Button>
          <Button type="button" size="sm" className="bg-[#7C3AED]" asChild>
            <Link href="/dashboard" target="_blank" rel="noopener noreferrer">
              Open dashboard
            </Link>
          </Button>
        </div>
      </div>
      {shareMsg ? (
        <p className="text-sm text-[#6ee7b7]" role="status">
          {shareMsg}
        </p>
      ) : null}

      <div className="grid gap-4 sm:grid-cols-3">
        <Card className="border-white/10 bg-white/[0.03]">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-white/45">
              Trust score
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-2xl font-semibold tabular-nums text-[#6ee7b7]">
              {agent.trustScore}%
            </p>
          </CardContent>
        </Card>
        <Card className="border-white/10 bg-white/[0.03]">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-white/45">
              Actions on record
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-2xl font-semibold tabular-nums text-white">
              {agent.totalEvents.toLocaleString("en-US")}
            </p>
          </CardContent>
        </Card>
        <Card className="border-white/10 bg-white/[0.03]">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-white/45">
              Policy version
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm font-mono text-white/80">
              {agent.policyVersion}
            </p>
          </CardContent>
        </Card>
      </div>

      <Tabs defaultValue="overview" className="w-full">
        <TabsList className="w-full justify-start overflow-x-auto sm:w-auto">
          <TabsTrigger value="overview">Overview</TabsTrigger>
          <TabsTrigger value="policy">Policy &amp; model</TabsTrigger>
          <TabsTrigger value="activity">Behavioral Record</TabsTrigger>
        </TabsList>
        <TabsContent value="overview" className="mt-6">
          <Card className="border-white/10 bg-white/[0.03]">
            <CardContent className="space-y-4 p-6">
              <p className="text-sm leading-relaxed text-white/70">
                This agent is bound to your workspace ledger. Every inference,
                tool call, and safety decision can produce a permanent
                receipt you can share with legal or customers. Use the{" "}
                <span className="text-white/85">Behavioral Record</span> tab for
                the timeline and downloadable receipts.
              </p>
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value="policy" className="mt-6">
          <Card className="border-white/10 bg-white/[0.03]">
            <CardContent className="space-y-3 p-6 font-mono text-xs text-white/70">
              <p>
                <span className="text-white/40">Manifest CID</span>
                <br />
                <span className="break-all text-[#c4b5fd]">
                  {agent.policyManifestCid}
                </span>
              </p>
              <p>
                <span className="text-white/40">Model fingerprint</span>
                <br />
                <span className="break-all">{agent.modelFingerprint}</span>
              </p>
              {agent.ledgerContract ? (
                <p>
                  <span className="text-white/40">Ledger contract</span>
                  <br />
                  <span className="break-all">{agent.ledgerContract}</span>
                </p>
              ) : null}
              <Button
                type="button"
                variant="secondary"
                size="sm"
                className="mt-2"
                onClick={() =>
                  void navigator.clipboard.writeText(agent.policyManifestCid)
                }
              >
                <Copy className="mr-1.5 h-3.5 w-3.5" />
                Copy manifest CID
              </Button>
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value="activity" className="mt-6">
          <div className="space-y-3">
            {sorted.length === 0 ? (
              <p className="text-sm text-white/50">No recent events for this agent.</p>
            ) : (
              sorted.map((ev) => {
                const v = verificationHuman(ev.verificationStatus);
                const badgeVariant =
                  v.variant === "success"
                    ? "success"
                    : v.variant === "destructive"
                      ? "destructive"
                      : "secondary";
                return (
                  <Card
                    key={ev.id}
                    className="border-white/10 bg-white/[0.03]"
                  >
                    <CardContent className="space-y-3 p-4">
                      <div className="flex flex-wrap items-center gap-2">
                        <Badge variant={badgeVariant}>{v.label}</Badge>
                        <span className="text-xs text-white/40">
                          {humanEventKind(ev.type)}
                        </span>
                      </div>
                      <p className="text-sm text-white/85">{ev.summary}</p>
                      <div className="flex flex-wrap gap-2">
                        <Button
                          type="button"
                          variant="outline"
                          size="sm"
                          className="gap-1"
                          onClick={() =>
                            window.open(
                              baseTxUrl(ev.anchored.txHash),
                              "_blank",
                            )
                          }
                        >
                          <ExternalLink className="h-3.5 w-3.5" />
                          Verify record externally →
                        </Button>
                        <Button
                          type="button"
                          variant="secondary"
                          size="sm"
                          className="gap-1"
                          onClick={() => {
                            const body = buildTrustReceipt(agent, ev);
                            const blob = new Blob([body], { type: "text/plain" });
                            const url = URL.createObjectURL(blob);
                            const a = document.createElement("a");
                            a.href = url;
                            a.download = `agentledger-${agent.id}-${ev.id}.txt`;
                            a.click();
                            URL.revokeObjectURL(url);
                          }}
                        >
                          <FileCheck className="h-3.5 w-3.5" />
                          Download receipt
                        </Button>
                        <Button
                          type="button"
                          variant="ghost"
                          size="sm"
                          onClick={() =>
                            void navigator.clipboard.writeText(
                              ev.anchored.txHash,
                            )
                          }
                        >
                          <Copy className="h-3.5 w-3.5" />
                          Copy tx
                        </Button>
                      </div>
                    </CardContent>
                  </Card>
                );
              })
            )}
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}
